title : 밤(hcooch2ch3) - Swift/iOS Blog
name: '임성민(밤) - Swift/iOS Blog'
description: '임성민(밤) - Swift/iOS Blog'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

collections:
  posts:
    title: Posts
    default_open: true
    output: true
  til:
    title: TIL
    default_open: false
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Posts
      permalink: /post/:title
  - scope:
      type: til
    values:
      title: TIL
      permalink: /til/:title

plugins:
  - jekyll-sitemap
