title : 밤(hcooch2ch3) - Swift/iOS Blog
name: '밤(hcooch2ch3) - Swift/iOS Blog'
description: '밤(hcooch2ch3) - Swift/iOS Blog'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'

collections:
  posts:
    title: Posts
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Posts
      permalink: /post/:title

plugins:
  - jekyll-sitemap
