title : 밤(hcooch2ch3) - Swift/iOS Blog
name: '밤(hcooch2ch3) - Swift/iOS Blog'
description: '밤(hcooch2ch3) - Swift/iOS Blog'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

collections:
  posts:
    title: Posts
    default_open: true
    output: true
  tiltwl:
    title: TIL/TWL
    default_open: false
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Posts
      permalink: /post/:title
  - scope:
      type: tiltwl
    values:
      title: TIL/TWL
      permalink: /tiltwl/:title

plugins:
  - jekyll-sitemap
